### ISSUE TITLE
Running different tasks for same server group

### ISSUE THREAD

**Issue by geekguy** [shipitjs/shipit#122]
Kind of related to this issue: https://github.com/shipitjs/shipit/issues/113

I understand, it's not a good practice to have different configuration for same server group.

Use case: 
We have two servers, we push same code to both the servers (same config). We just don't want to run some particular task on one of the servers. (For Eg: nginx reload on a cron server).

Is it possible? If not, is there any work around for this?

**Comment by timkelty** [comment]
Couple alternatives:

- Make your task first check the server, matching against `hostname` or ip.
- If value matches, continue with your task

Alternatively you could just have 2 different environments sharing the same config, and always deploy them together: `shipit production deploy && shipit production2 deploy`

**Comment by geekguy** [comment]
@timkelty : Din't get the first one. Where should I put that check ?

**Comment by timkelty** [comment]
@geekguy Sorry, my explanation didn't make much sense.

What I meant was, you could do something like: 
```shipit.remote('if [[ $(hostname -s) = "MyHost" ]]; then nginx -s reload; fi');```

Not ideal, but it should work

**Comment by timkelty** [comment]
Sorry, first option didn't make sense. What I meant was something like:

```
shipit.remote('if [[ $(hostname -s) = "MyHost" ]]; then nginx -s reload; fi');
```

**Comment by travco** [comment]
Hey @geekguy, still having issues or did you get it all sorted out?

If it is resolved, if you could close the issue that would be great!

**Comment by geekguy** [comment]
Hi @travco : Yes. That solves the problem for now. But I am not sure if that's the proper approach for this issue. IMHO, shipit should have this feature. If that's not the case, happy to close.

**Comment by travco** [comment]
Do you have something to suggest @geekguy ? I'm not really core to the shipit team, but I will say that I don't think there's "pretty" solution to this, as the ones presented thus far are: 

(In order of degrading personal opinion)
- Putting a script (shell or otherwise) of the same name on all servers in the group that is just executed by shipit. The ones that don't need anything done can have a do-nothing script, the ones that do have it there forever. (Fast, same config and commands to all servers, commands wouldn't need to change even if you get additional servers. However it requires the effort to make the scripts, and hopefully no server needs to get wiped, lest you lose it.)
- Hostname/IP/Env conditional commands baked directly into the server, (relatively fast, a little archaic and hacky)
- Multiple environs. using the same config that just get deployed one-after-another (Which is going to be slow, no matter how you cut it)
- Environment variable-based commands, passed individually to servers (less quick, requires multiple commands and some "dancing around" to get it to work, Bad practice as you said yourself, defeats the purpose of groups)
- Completely separate configs, separating the servers out of their groups (Extra time, extra config, a cop-out solution)

I can't really think of a solution beyond making conditional commands really a part of shipit, but that would be a departure from it's general purpose, and isn't really more elegant than the ones /\ above.

**Comment by timkelty** [comment]
@geekguy Closing for now, but I'll keep this in mind.

**Comment by mochini** [comment]
I just released a new npm module that monkey patches the `remote()` and `remoteCopy()` functions to accept a `role` option that lets you target specific groups of servers. You can find it here:

https://www.npmjs.com/package/shipit-roles

**Comment by neoziro** [comment]
@mochini package not found

**Comment by mochini** [comment]
Try the link again - I think something was up with npmjs.org. It didn't work for me when I just clicked the link, but then I clicked it again and it was fine. Weird...

You can also find it here:

https://github.com/mahaplatform/shipit-roles

**Comment by mochini** [comment]
btw, @neoziro, if you like this functionality, I'd be happy to submit a pull request to the main shipit github repo. I think it would be a good enhancement to your existing functionality and it's a feature that I'm certain a lot of your users would use.

Thanks for doing all this work - it's really exactly what I was looking for on my project.

**Comment by neoziro** [comment]
@mochini yes thanks, I will think about it, for now I try to stabilize all things.

**Comment by mochini** [comment]
@neozero here you go:

https://github.com/shipitjs/shipit/pull/161

I updated the `initSshPool`, `remote()`, and `remoteCopy()` functions to address segmented pools of servers rather than a single connection pool. If you don't add a `role` option to your server config and/or use the `role` option when calling `remote()` or `remoteCopy()`, it basically ignores this new functionality. 

I fixed the tests that I broke and added a few more to exercise my additions. I even updated the README!

Hope you like it. If not, no biggie - I'll still maintain these features in my `shipit-roles` module, but I think it makes you tool even more powerful and useful!
