### ISSUE TITLE
Deploy from local environment using Windows

### ISSUE THREAD

**Issue by jdnichollsc** [shipitjs/shipit#126]
Hello guys,

Is possible to execute the commands from my Windows enviroment?

Thanks, Nicholls

**Comment by timkelty** [comment]
It's possible, but you'll still need rsync installed somehow (Cygwin, e.g.).
Untested, though.

**Comment by jdnichollsc** [comment]
See the error from Windows: http://screencast.com/t/go4OHbum5qR

**Comment by timkelty** [comment]
Right, its going to be relying on several Unix commands (like `rm`). `shipit-deploy` is not going to work without something like Cygwin giving you these commands. Shipit itself _may_ work, but you'd have to write a deploy script/plugin that worked with windows otherwise.

**Comment by travco** [comment]
@jdnichollsc, I'd suggest trying out the git bash for windows: https://git-for-windows.github.io/
I personally haven't verified if it has rsync baked in by default, but it does wrapper around most linux commands so that they can be executed natively in the windows environment. 

If it doesn't actually have rsync baked in, you can bring the package in so that they can be used: http://superuser.com/questions/701141/how-to-add-more-commands-to-git-bash-shell?answertab=votes#tab-top
(your going to be wanting to referencing the MSYS part of that answer)

Although some parts of the node/npm ecosystem have alternate versions that work in windows directly, most of them are based off of UNIX commands. It's a little bit of a learning curve if your a DOS junky, but there's a lot more you'll be able to do with (minimal) hassle in -this- ecosystem at least.

Suggest Closing?

**Comment by jdnichollsc** [comment]
Thanks for your help my friend! :+1:
