### ISSUE TITLE
npx: command not found: shipit

### ISSUE THREAD

**Issue by jake-harris** [shipitjs/shipit#253]
I'm attempting to test this project for the first time and receive the following response:

```
$ npx shipit development deploy
npx: installed 213 in 5.849s
command not found: shipit
```

For reference, here's my `shipitfile.js`:

```
// shipitfile.js
module.exports = shipit => {
    // Load shipit-deploy tasks
    require('shipit-deploy')(shipit)

     const project = 'myproject.com'

    shipit.initConfig({
        default: {
            deployTo: `~/${project}`,
        },
        development: {
            servers: 'dev.myservers.com',
        },
    })
}
```

Finally, I should mention `npx` works fine with other projects, e.g.:

```
$ npx cowsay It works
npx: installed 10 in 0.946s
 __________
< It works >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

For reference, node was installed via brew on Mac OS 10.14.6

Program|Version
--|--
node|12.10.0
npm|6.11.3
npx|6.11.3

I'm happy to provide any additional info I can to help troubleshoot.

**Comment by schwarmco** [comment]
The problem is, that you don't have shipit-cli and shipit-deploy installed.

What happens then is, that `npx` tries to auto-install the `shipit` binary from the [shipit module](https://www.npmjs.com/package/shipit) which is a completely different thing.

Read more about that functionality in this issue: https://github.com/npm/npx/issues/9

To make it work for you, just do: `npm i shipit-cli shipit-deploy && npx shipit`

**Comment by gregberge** [comment]
`npx shipit-cli` should work, there is a single binary in the project so it will use it.
