### ISSUE TITLE
Consider using childProcess.spawn instead of childProcess.exec

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#62]
I'm not sure if this is related to some problems I've been having running `npm install`, but it seems possible. https://github.com/shipitjs/shipit/issues/57

[You're using `child_process.exec` for `shipit.local` commands](https://github.com/shipitjs/shipit/blob/master/lib/shipit.js#L196). Given that those commands may be lengthy or intensive (`npm install`, e.g.), it seems that maybe we should be using `child_process.spawn`?

**Comment by neoziro** [comment]
@timkelty yes but there is a lot of work done in `child_process.exec`, so there will be a lot of code to do if we want to use `child_process.spawn` instead.

**Comment by timkelty** [comment]
We _could_ do something like this in the meantime:

```
    options = _.defaults(options || {}, {
      maxBuffer: 1000 * 1024,
      spawn: false,
      spawnArgs: []
    });

    var stdoutWrapper = new LineWrapper({prefix: '@ '});
    var stderrWrapper = new LineWrapper({prefix: '@ '});

    var child = options.spawn ? childProcess.exec(command, options.spawnArgs, options) : childProcess.exec(command, options);

    child.on('error', function(err) {
      return reject(err);
    });

    child.on('exit', function(code) {
      return resolve({
        child: child,
        stdout: child.stdout[0],
        stderr: child.stderr[0]
      });
    });
```

However, I just tried that, and it still didn't fix the issues I'm having with `npm install`.

**Comment by timkelty** [comment]
Maybe this should be a 2.x consideration.

**Comment by mscdex** [comment]
There's also [`ssh2`](https://github.com/mscdex/ssh2) if you want to avoid child processes altogether :sunglasses:

**Comment by travco** [comment]
@timkelty - Had to do some research on this one, because I know Node operates a little differently. Still not terribly familiar with it, so take it with a grain of salt.

Node doesn't really have massive differences between how spawn and exec are created and operate on the system level. Unlike certain other programming languages/dialects, both and spawn and exec async commands are non-blocking and independantly operative from the parent process.
Per: https://nodejs.org/api/child_process.html#child_process_child_process
> ...the child_process module provides ... alternatives to child_process.spawn() ... Note that each of these alternatives are implemented on top of child_process.spawn().

The only real difference is that spawn produces a process that still has the capability to engage in assisted/shared permission IPC (Inter Process Communication) with the parent (making it great deal more integrated). Because it's more integrated, spawn is great for making child processes that are going to distribute the workload of a single task/dataset, and communicate/cooperate as they run.

Thus, migrating to using spawn would have a pretty minimal effect beyond giving someone more programming work. Because I just don't think shipit is commonly being used as a startup-sequence for [SIMD](https://en.wikipedia.org/wiki/SIMD) compute work.

Probably can close this issue.

**Comment by neoziro** [comment]
@travco thanks for the analyse, ssh-pool v2 will still use exec.

**Comment by weotch** [comment]
I recently ran into an issue with exec that was fixed by switching to spawn.  Part of my deploy runs a webpack-based compilation task (`NODE_ENV=production webpack --progress`) through a package.json script (`yarn minify`).  Running the command directly takes ~40s.    On a current project, this was taking ~13**min** to execute through shipit:

```js
shipit.blTask('compile', ['yarn'], function() {
  return shipit.local('yarn minify', {
    cwd: workspace
  });
});
```

Switching to using spawn brought the time back down to ~40s:

```js
shipit.blTask('compile', ['yarn'], function(cb) {
  var minify;
  minify = child_process.spawn('yarn', ['minify'], {
    cwd: workspace
  });
  minify.stdout.pipe(process.stdout);
  minify.stderr.pipe(process.stderr);
  return minify.on('close', cb);
});
```

Maybe `shipit.localSpawn()` could be added for long running, cpu heavy tasks?

**Comment by neoziro** [comment]
@weotch interesting, we should definitely consider it if it's a game changer for webpack.
