### ISSUE TITLE
impossible to run shipit if uid doesn't have access to home directory

### ISSUE THREAD

**Issue by brycefisher** [shipitjs/shipit#70]
### PROBLEM

Trying to run a shipit command when the process uid doesn't have access to the home directory causes immediate failure.

### EXPECTED BEHAVIOR

Shipit command should succeed (possibly with warning) unless that command _explicitly_ depends on use of the home directory.

### STEPS TO REPRODUCE

 1. Setup a simple shipit config
 2. `$ export HOME=<inaccessible directory>`
 3. Run a shipit command

Technically, this is a problem with the v8flags dependency (I'll file an issue there as well). This was a somewhat difficult error to fix in a good way since it required us to change our AMIs redeploy our machines, and it was very unexpected.

There's no mention I could find in the documentation stating that access to the home directory by process uid is a requirement for using shipit, nor even that any config will be used from the home directory. 

### PROPOSED CHANGES

 * I propose, at a minimum, that this requirement be documented in the README, a troubleshooting doc, or the wiki until such time as this is not a requirement.
 * As a "deeper" fix, I would happy to provide a PR that allows shipit to avoid requiring and passing an instance of v8flags to liftoff.

**Comment by brycefisher** [comment]
My apologies here, but I don't understand what v8flags is doing [here](https://github.com/shipitjs/shipit/blob/master/bin/shipit#L15). There's no options explicitly passed (such as `--harmony` and [the like](https://github.com/tkellen/js-liftoff/blob/master/README.md#optsv8flags)). 

Is there some way to pass v8flag values to the liftoff object? It's a little bit magical, and I'm lost on why the v8flags dependency is needed at all (though liftoff seems really cool!)

**Comment by tkellen** [comment]
If you run `node --v8-options` you'll see a list of all possible flags you can use to augment v8.  Currently, there is no way in node to access this listing programatically, so I spawn a process to capture these options. Doing this every invocation of a command line tool is unacceptable from a performance standpoint, so the output is cached in the user's home directory (or, if it can't be found, the os temp directory).

If any flags passed to a Liftoff-powered cli are in the array of v8flags, Liftoff will detect and respawn the command correctly. For example, `shipit --harmony blah` internally runs `node /path/to/shipit --harmony blah`. Because Liftoff knows which flags should be applied to v8, it respawns it as `node --harmony /path/to/shipit blah`.

All of that said, let's address this issue on the v8flags repo!

**Comment by brycefisher** [comment]
@tkellen thanks for the detailed usage information! That does help explain how what v8flags does in this module. Issue opened on v8flags!

**Comment by travco** [comment]
Hey @brycefisher, since this got resolved on the v8flags end - is there any latent issue for you?

If it's resolved, if you could close the issue that would be great!
