### ISSUE TITLE
Escaping commands for shipit.remote/local

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#91]
I recently had an issue with a `shipit.remote` command with a `$` in it:

`mysql -u'xxx' -p'xxx$xx' -h'127.0.0.1' -D db_production`

For this to work properly, the `$` needs to be escaped (`-p'xxx\$xx'` ).

What is the best way to deal with this?

Is this something that `shipit.remote`/`ssh-pool` should do, or should I have to make sure my strings are escaped before I pass them to `shipit.remote`?

**Comment by neoziro** [comment]
@timkelty hmm it should be done in the project, we already do it for quotes

**Comment by timkelty** [comment]
After a bit more investigating, the problem is actually related to quotes.

In my example, `mysql -u'xxx' -p'xxx$xx' -h'127.0.0.1' ` works fine on the server, because of the single quotes.

However, when shipit runs it, the acutal command is `ssh foo@server.com "mysql -u'xxx' -p'xxx$xx' -h'127.0.0.1' "`. In this instance, because the outer double quotes, the dollar needs to be escaped within context of the `ssh` command.

**Comment by neoziro** [comment]
@timkelty OK let's escape $

**Comment by nkovacs** [comment]
It would be better to use single quotes in the ssh command, like this:

```
ssh foo@server.com 'mysql -u'\''xxx'\'' -p'\''xxx$xx'\'' -h'\''127.0.0.1'\'''
```

(The last `''` could be removed, but it's simpler to just leave it.)

Since you can't have single quotes inside single quotes (even escaped), you have to close the first single-quoted string, immediately add a literal single quote (that's why it's escaped), then continue with another single-quoted part of the string.

So what you have to do is replace each single quote inside the command with `'\''` (or `'"'"'`) and add single quotes around it before passing it to ssh: https://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings
