### ISSUE TITLE
ssh2 vs ssh-pool

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#92]
Not suggesting that we should switch for no reason, but just curious is dropping ssh-pool in favor of ssh2 is on the table at all?

Just one less thing to manage, and ssh2 seems to have  lots of features that may be useful (like key authentication)

**Comment by neoziro** [comment]
@timkelty why not, I chose to make a module that run command because it was simpler.

**Comment by basgren** [comment]
Hi guys. Maybe I missed something, but I thought that Shipit supports key authentication. Is it true?

Actually I have issues with Jenkins + Shipit. When I try to run Shipit script on my local machine and deploy application to target host using ssh-key authentication, everything works fine. But when I run Shipit script from Jenkins job (on a different server), it fails to connect to target host. BUT i'm prety sure that Jenkins server keys are authorized on target host, as simple `ssh` command works well. So I'm curious whether this is due to lack of some functionality in ssh-pool or I need to dig deeper with Jenkins server configuration.

Thanks.

**Comment by basgren** [comment]
Ah, sorry. I solved the issue - I should have specified full path to **private** key, not to public key. So this config option finally worked both locally and in Jenkins:
```js
shipit.initConfig({
  default: {
    ...
    key: process.env['HOME'] + '/.ssh/id_rsa', // Path to PRIVATE file
    ...
  }
}
```

**Comment by timkelty** [comment]
Good!
We should probably update the README to note this.
